=== Suyash0028/Http5222/JLab6-SuyashKulkarni/book.dtd
<!ELEMENT books (book*)>
<!ELEMENT book (title,language,author+)>
<!ATTLIST book 
    ISBN CDATA #REQUIRED
    yearPublished CDATA #REQUIRED
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT author (name, email?, number?, bio)>
<!ELEMENT name (first, middle?, last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT middle (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT bio (#PCDATA)>

=== Suyash0028/Http5222/JLab6-SuyashKulkarni/book.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE books SYSTEM "book.dtd">
<books>
    <book ISBN="123456781241" yearPublished="1996">
        <title>Learn Javascript</title>
        <language>English</language>
        <author>
            <name>
                <first>John</first>
                <middle>James</middle>
                <last>Doe</last>
            </name>
            <email>John.Doe@gmail.com</email>
            <number>2268812952</number>
            <bio>John is a software developer, teach you best and easy way to lear javascript.</bio>
        </author>
    </book>
    <book ISBN="" yearPublished="">
        <title>Learn C#</title>
        <language>English</language>
        <author>
            <name>
                <first>Christine</first>
                <last>Bittle</last>
            </name>
            <email>Christine.Bittle@gmail.com</email>
            <number>2268812952</number>
            <bio>Christine is a teacher at humber college and teaches the easiest way to learn c#.</bio>
        </author>
    </book>
</books>
